### ISSUE TITLE
[BUG]:Uncaught (in promise) bad-precaching-response in production

### ISSUE THREAD

**Issue by RafDiMartino** [ImBIOS/next-pwa#100]
### Description of the bug

I am following this tutorial [https://next-pwa.imam.dev/usage](https://next-pwa.imam.dev/usage),
all works fine until I send it to production, then I get this error, any suggestion on how to fix it?

<img width="614" alt="Screenshot 2023-07-25 at 15 44 06" src="https://github.com/ImBIOS/next-pwa/assets/69420740/21c0bcd4-8f32-41c8-933c-2fa4c0aaf436">

### Environment

N/A

### Steps To Reproduce

N/A

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ImBIOS/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ImBIOS/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by IBastawisi** [comment]
exclude it with `buildExcludes: [/.*manifest.json$/]`

**Comment by RafDiMartino** [comment]
I managed to fix the error with this:  `buildExcludes: ["app-build-manifest.json"]`
